package com.myspace.authworkflow;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class AuthRequestDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Auth Request ID")
	private java.lang.Long authRequestId;

	@org.kie.api.definition.type.Label("Request Type ")
	private java.lang.String requestType;

	@org.kie.api.definition.type.Label("ICD10 Codes")
	private java.lang.String icd10;

	@org.kie.api.definition.type.Label(value = "Status")
	private java.lang.String status;

	public AuthRequestDO() {
	}

	public java.lang.Long getAuthRequestId() {
		return this.authRequestId;
	}

	public void setAuthRequestId(java.lang.Long authRequestId) {
		this.authRequestId = authRequestId;
	}

	public java.lang.String getRequestType() {
		return this.requestType;
	}

	public void setRequestType(java.lang.String requestType) {
		this.requestType = requestType;
	}

	public java.lang.String getIcd10() {
		return this.icd10;
	}

	public void setIcd10(java.lang.String icd10) {
		this.icd10 = icd10;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public AuthRequestDO(java.lang.Long authRequestId,
			java.lang.String requestType, java.lang.String icd10,
			java.lang.String status) {
		this.authRequestId = authRequestId;
		this.requestType = requestType;
		this.icd10 = icd10;
		this.status = status;
	}

}